from typing import Any

import torch
import torch.nn as nn
from torch_geometric.data import Batch
from torch_geometric.nn import global_mean_pool

from ugtsdti.core.registry import MODELS


@MODELS.register("baseline_student")
class BaselineStudent(nn.Module):
    """
    Ultra-lightweight Baseline/Dummy Model for Pipeline Validation.
    - Drug Branch: Directly pools raw RDKit features (No Graph Convolutions).
    - Prot Branch: Uses a simple nn.Embedding matrix and pools over sequences (No Transformers).
    - Fusion: Concat -> Linear -> Logit
    """

    def __init__(
        self,
        drug_raw_dim: int = 7,  # Default RDKit atoms features
        prot_vocab_size: int = 50,  # Max typical amino acid vocab
        prot_embed_dim: int = 32,
        hidden_dim: int = 64,
        dropout: float = 0.1,
    ):
        super().__init__()

        # Protein (sequence) branch
        self.protein_embedding = nn.Embedding(prot_vocab_size, prot_embed_dim, padding_idx=0)
        self.protein_proj = nn.Linear(prot_embed_dim, hidden_dim)

        # Drug (graph) branch — raw atom feature projection, no GCN
        self.drug_proj = nn.Linear(drug_raw_dim, hidden_dim)

        # Fusion
        self.fusion = nn.Sequential(
            nn.Linear(hidden_dim * 2, hidden_dim),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(hidden_dim, 1),
        )

    def forward(self, batch: dict[str, Any]) -> dict[str, torch.Tensor]:
        """
        Forward pass.
        Expects a Dictionary generated by the Multimodal DataLoader.
        """
        ### 1. Drug branch ###
        drug_graph: Batch = batch["drug"]
        atom_features, graph_batch_idx = drug_graph.x.float(), drug_graph.batch

        drug_emb = global_mean_pool(self.drug_proj(atom_features), graph_batch_idx)  # [B, hidden_dim]

        ### 2. Protein branch ###
        target_ids: torch.Tensor = batch["target_ids"]  # [B, L]
        target_mask: torch.Tensor = batch["target_mask"]  # [B, L]

        protein_tokens = self.protein_embedding(target_ids)  # [B, L, prot_embed_dim]
        protein_tokens = protein_tokens * target_mask.unsqueeze(-1).float()

        seq_lengths = target_mask.sum(dim=1, keepdim=True).clamp(min=1)
        protein_emb = self.protein_proj(protein_tokens.sum(dim=1) / seq_lengths)  # [B, hidden_dim]

        ### 3. Fusion ###
        pair_emb = torch.cat([drug_emb, protein_emb], dim=1)  # [B, hidden_dim * 2]
        logits = self.fusion(pair_emb)  # [B, 1]

        return {"logits": logits}
